development:
  adapter: postgresql
  encoding: unicode
  database: tun
  pool: 5
  username: tun
  host: 192.168.1.116

development:
  adapter: postgresql
  encoding: unicode
  database: tun
  pool: 5
  username: tun
  host: 192.168.1.116
